### ISSUE TITLE
[2.2.1] `until_front_of_line` reports null timestamps and continues without waiting

### ISSUE THREAD

**Issue by ghost** [eddiewebb/circleci-queue#104]
### RELEASE CANDIDATE READY

➡️ **Potential fix for this issue is ready** ⬅️

For anyone willing to validate on non-critical workloads, please use `eddiewebb/queue@dev:506` and report any issues on #112 

---

### Orb version

2.2.1

### What happened

I have this configuration:

```
      - queue/until_front_of_line:
          only-on-branch: master
          only-on-workflow: orange_build
          block-workflow: true
          time: '10'
          circleci-api-key: CIRCLECI_TOKEN
```

But when two concurrent `orange_build` workflows runs the second one reports null timestamp and continues:

```
This Workflow Timestamp: null
Oldest Workflow Timestamp: null
Front of the line, WooHoo!, Build continuing
```

Downgrading to 1.8.4 solves the issues. But of course missing the new `only-on-workflow` parameter.

### Expected behavior

Should wait for the previous workflow to finish.
