### ISSUE TITLE
[3.1.4] How to block workflows that are triggered with commits and tags

### ISSUE THREAD

**Issue by ArthurKnoep** [eddiewebb/circleci-queue#130]
### Orb version

3.1.4

### What happened

I'm working on a project that defines two main CircleCI workflows:
- One is triggered on every commit on the main branch for staging and run something similar to this:
  -  [block_e2e] -> [build_deploy_e2e] -> [run_e2e] -> [block_deploy_stg] -> [build_stg] -> [deploy_stg]
- One is triggered on tags on the main branch and run something very much similar but deploys on production instead:
   -  [block_e2e] -> [build_deploy_e2e] -> [run_e2e] -> [block_deploy_prod] -> [build_prod] -> [deploy_prod]

The issue I have is that the building, deploying and testing of the end to end tests must not ran concurrently, whatever the workflow.

For the `block_e2e` job of the "commit" workflow I'm using the following definition
```yaml
      - queue/block_workflow:
          name: block_e2e
          max-wait-time: '180'
          this-branch-only: false
          job-regex: '^build_deploy_e2e|run_e2e$'
          my-pipeline: << pipeline.number >>
          confidence: '2'
```
For the `block_e2e` job of the "tag" workflow, I'm using the same definition but I'm adding a `filters` defintion to trigger the job in CircleCI and a `tag-pattern`:
```yaml
      - queue/block_workflow:
          filters:
            tags:
              only: /^v.*$/
            branches:
              ignore: /.*/
          name: block_e2e
          tag-pattern: '^v.*$'
          max-wait-time: '180'
          this-branch-only: false
          job-regex: '^build_deploy_e2e|run_e2e$'
          my-pipeline: << pipeline.number >>
          confidence: '2'
```

The issue I'm having is that by adding the `tag-pattern` variable it ignores the workflow running for the "commit" workflow (at least from what I understand of [this line](https://github.com/eddiewebb/circleci-queue/blob/edfb701b59d73a64dcc4c94af6d42ed4a3fe1f9b/scripts/loop.bash#L139)

But if I don't specify the `tag-pattern` parameter the queue blocker won't run, because of [this condition](https://github.com/eddiewebb/circleci-queue/blob/edfb701b59d73a64dcc4c94af6d42ed4a3fe1f9b/scripts/loop.bash#L54)

### Expected behavior

I would like to have my workflow blocked according to every workflow (both triggered by tags or commits)
