### ISSUE TITLE
[3:2:1] Job is also waiting for cancelled jobs

### ISSUE THREAD

**Issue by darrikonn** [eddiewebb/circleci-queue#138]
### What happened

**queue/block_workflow**
```
This build (63479), pipeline (56632) is queued, waiting for build(46706) pipeline (45634) to complete.
```

Build `46706` from pipeline `45634` is cancelled (1 month old), but current job is being queued.
Restarting the `46706` in order for it to fail won't succeed either, since only the previous job is being used.

### Expected behavior

Current job shouldn't be queued from cancelled jobs/workflows.

**Comment by eddiewebb** [comment]
Thanks for report Darri.

Can you open
https://circleci.com/api/v1.1/project/${VCS_TYPE}/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}?filter=running
in your browser(replacing variables with your project info)

And confirm you see the job in question, and any non sensitive details
about status.

**Comment by eddiewebb** [comment]
Also share details on what vcs type you're using.

**Comment by darrikonn** [comment]
This is interesting:
```json
"canceled": false,
"status": "running",
```

but it's indeed cancelled:
<img width="128" alt="image" src="https://github.com/user-attachments/assets/c2446daa-2d7a-423d-a9aa-fab64ab29340">

**Comment by eddiewebb** [comment]
I think you'll need support to fix that. You can send them a job link to
investigate.

support.circleci.com

**Comment by djanicekpach** [comment]
Just a heads up, today we are seeing or job now waiting on a cancelled job from February. I haven't had a chance to dig deeper but my hunch is something with the new job status released today from circle-ci. I'm going to submit a support ticket to them. https://circleci.com/changelog/new-job-type-no-op-job-can-make-complex-workflows-simple/

**Comment by eddiewebb** [comment]
We've built a couple new job types as part of larger work, and pretty
exciting as they come together. Also some exciting updates that will
eventually impact this orb, but I'm not sure why they would affect old job
statuses. I can ping the team internally to see if any recent changes would
affect the API status values.

**Comment by eddiewebb** [comment]
Team confirmed No-op job would **not** affect API status for existing jobs. Support ticket with specific build links can help our team investigate what's unique to your situations though.

I'm going to close this issue as there is not anything in the orbs logic at fault however.

**Comment by eddiewebb** [comment]
@darrikonn - does the job in question have a "stopped_at" in the API?  

(Might just update the orb to ignore jobs older than XX days or if additional field adds clarity to remove them from consideration)

**Comment by darrikonn** [comment]
Nope:
```yaml
{
...,
"vcs_tag": null,
"build_num": 46706,
"infrastructure_fail": false,
"committer_email": null,
"previous": {
"build_num": 46705,
"status": "infrastructure_fail",
"build_time_millis": 84833
},
"status": "running",
"committer_name": null,
"retries": [
  63468
],
"subject": null,
"vcs_type": "github",
"timedout": false,
"dont_build": null,
"lifecycle": "running",
"stop_time": null,
"ssh_disabled": false,
"build_time_millis": null,
"picard": null,
"circle_yml": null,
"messages": [],
"is_first_green_build": false,
"job_name": null,
"start_time": "2024-10-28T14:52:47.486Z",
"canceler": null,
"all_commit_details": [],
"platform": "1.0",
"outcome": null,
"author_name": null,
"node": null,
"queued_at": "2024-10-28T14:51:59.988Z",
"canceled": false,
"author_email": null
}
```
