### ISSUE TITLE
The orb seems to be broken

### ISSUE THREAD

**Issue by mbelang** [eddiewebb/circleci-queue#14]
The orb is always using the MOCK response

```
Max Queue Time: 10 minutes.
Using test mock response
Only blocking execution if running previous jobs matching: deploy-dev
Oldest job: 
```

Here is my config:
```
      - queue/until_front_of_line:
          consider-job: true
          consider-branch: true
          dont-quit: true
```

And I do not have the `TESTING_MOCK_RESPONSE` variable set
