### ISSUE TITLE
Feature request: only-on-branch accept multiple values

### ISSUE THREAD

**Issue by artemgurzhii** [eddiewebb/circleci-queue#25]
On my project, I have 3 production branches. On each of it if tests pass successfully - deployment process starts, which I need to queue to prevent multiple parallel deployments processes. 

Mu current circleci config looks like

```yml
workflows:
  version: 2.1
  test_and_deploy:
    jobs:
      - queue/block_workflow:
          block-workflow: true
          consider-branch: true
          only-on-branch: branch-1
          time: '10'
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only:
                - branch-1
                - branch-2
                - branch-3
```

what I propose:

```yml
workflows:
  version: 2.1
  test_and_deploy:
    jobs:
      - queue/block_workflow:
          block-workflow: true
          consider-branch: true
          only-on-branch: 
            - branch-1
            - branch-2
            - branch-3
          time: '10'
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only:
                - branch-1
                - branch-2
                - branch-3
```
