### ISSUE TITLE
until_front_of_line doesn't block on Alpine images

### ISSUE THREAD

**Issue by dcelasun** [eddiewebb/circleci-queue#29]
Perhaps I'm doing something wrong, but I can't get `until_front_of_line` to work. The job config looks like this:

```yaml
deploy-step:
    docker:
      - image: alpine:3.9
    steps:
      - checkout
      - run:
          name: Install curl and jq
          command: |
            apk add --no-cache curl jq
      - queue/until_front_of_line:
          time: '10'
          only-on-branch: develop
          block-workflow: true
      - run:
          command: # some deploy command
```

Then I push two commits to `develop` with ~10 seconds between them. The log from the first job:

```
develop queueable
This build will block until all previous builds complete.
Max Queue Time: 10 minutes.
Only blocking execution if running previous jobs on branch: develop
Attempting to access CircleCI api. If the build process fails after this step, ensure your CIRCLECI_API_KEY is set.
API access successful
Orb parameter block-workflow is true.
This job will block until no previous workflows have *any* jobs running.
Oldest job: 
This Workflow Timestamp: "2019-09-04T12:33:17+01:00"
Oldest Workflow Timestamp: "2019-09-04T12:33:17+01:00"
Front of the line, WooHoo!, Build continuing
```
and the second one:
```
develop queueable
This build will block until all previous builds complete.
Max Queue Time: 10 minutes.
Only blocking execution if running previous jobs on branch: develop
Attempting to access CircleCI api. If the build process fails after this step, ensure your CIRCLECI_API_KEY is set.
API access successful
Orb parameter block-workflow is true.
This job will block until no previous workflows have *any* jobs running.
Oldest job: 
This Workflow Timestamp: "2019-09-04T12:33:27+01:00"
Oldest Workflow Timestamp: "2019-09-04T12:33:17+01:00"
Front of the line, WooHoo!, Build continuing
```

As you can see, `oldest workflow timestamp` is earlier than `this workflow timestamp`, but the build continues. Any ideas?
